import { APP, MARKETPLACE_TOTAL_FEE } from 'configuration'

export const APP_FEE = MARKETPLACE_TOTAL_FEE

// * APP NAME CONSTANT
export const APP_NAME = APP || 'SITE_STORAGE'

// * REQUEST STATUS CONSTANT
export const IS_PENDING = 'PENDING'
export const IS_SUCCESS = 'SUCCESS'
export const IS_FAILURE = 'FAILURE'

// * LOGIN/SIGNUP CONSTANTS
// ! Attention : No signup action required, because in backend, if no user, save user.
export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGOUT = 'DO_LOGOUT'

// * PROFILE CONSTANTS
export const DO_REQUEST_PROFILE = 'DO_REQUEST_PROFILE'
export const DO_UPDATE_PROFILE = 'DO_UPDATE_PROFILE'

// * COLLECTION CONSTANTS
export const DO_REQUEST_COLLECTIONS = 'DO_REQUEST_COLLECTIONS'
export const DO_UPDATE_COLLECTIONS = 'DO_UPDATE_COLLECTIONS'

// * USER CONSTANTS
export const DO_REQUEST_CREATORS = 'DO_REQUEST_CREATORS'
export const DO_REQUEST_USER = 'DO_REQUEST_USER'
export const DO_UPDATE_USER = 'DO_UPDATE_USER'

// * TOKEN CONSTANTS
export const DO_REQUEST_TOKENS = 'DO_REQUEST_TOKENS'
export const DO_REQUEST_TOKENS_BY_COLLECTION_ID = 'DO_REQUEST_TOKENS_BY_COLLECTION_ID'
export const DO_CREATE_TOKEN = 'DO_CREATE_TOKEN'
export const DO_UPDATE_TOKEN = 'DO_UPDATE_TOKEN'
export const DO_REQUEST_TOKEN = 'DO_REQUEST_TOKEN'

export const DO_REQUEST_AUCTION_TOKENS = 'DO_REQUEST_AUCTION_TOKENS'
export const DO_REQUEST_TOKEN_OFFERS = 'DO_REQUEST_TOKEN_OFFERS'
export const DO_UPDATE_TOKEN_OFFERS = 'DO_UPDATE_TOKEN_OFFERS'
export const DO_REQUEST_TOKEN_VIEWS = 'DO_REQUEST_TOKEN_VIEWS'
export const DO_UPDATE_TOKEN_VIEWS = 'DO_UPDATE_TOKEN_VIEWS'
export const DO_REQUEST_TOKEN_LIKES = 'DO_REQUEST_TOKEN_LIKES'
export const DO_UPDATE_TOKEN_LIKES = 'DO_UPDATE_TOKEN_LIKES'
